import type { Metadata } from "next";
import { DM_Sans, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { UnitsProvider } from "@/providers/UnitsContext";
import { SavedPlacesProvider } from "@/providers/savedPlaces";
import { DarkModeProviders } from "@/providers/DarkModeProviders";
import Navbar from "@/components/nav/Navbar";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#ffffff" />
        {/* Preload */}
        <link rel="preload" as="image" href="/bg-today-small.svg" />
        <link rel="preload" as="image" href="/bg-today-large.svg" />
        <link
          rel="preconnect"
          href="https://api.open-meteo.com"
          crossOrigin=""
        />
      </head>
      <body
        className={`${dmSans.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        <DarkModeProviders>
          <UnitsProvider>
            <SavedPlacesProvider>
              <Navbar />
              {children}
            </SavedPlacesProvider>
          </UnitsProvider>
        </DarkModeProviders>
      </body>
    </html>
  );
}
